[versions]
paper-api = "1.21.5-R0.1-SNAPSHOT"
paper-run = "1.21.7"
crate = "4.0.0-RC.5"
commandapi = "10.1.2"

[libraries]
# Core dependencies
annotations = "org.jetbrains:annotations:26.0.2"
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
morepaperlib = "space.arim.morepaperlib:morepaperlib:0.4.4"

# API dependencies
javasemver = "io.github.milkdrinkers:javasemver:1.0.2"
versionwatch = "io.github.milkdrinkers:versionwatch:1.0.2"
wordweaver = "io.github.milkdrinkers:wordweaver:0.0.7"
crate-api = { module = "io.github.milkdrinkers:crate-api", version.ref = "crate" }
crate-yaml = { module = "io.github.milkdrinkers:crate-yaml", version.ref = "crate" }
colorparser = "io.github.milkdrinkers:colorparser-paper:4.1.0"
threadutil-bukkit = "io.github.milkdrinkers:threadutil-bukkit:1.2.0"
commandapi-shade = { module = "dev.jorel:commandapi-bukkit-shade-mojang-mapped", version.ref = "commandapi" }
triumph-gui = "dev.triumphteam:triumph-gui-paper:3.1.13"
betonquest = "org.betonquest:betonquest:3.0.0-20251102.142314-419"

# Plugin dependencies
citizens = "net.citizensnpcs:citizens-main:2.0.39-SNAPSHOT"
settlers = "io.github.milkdrinkers:settlers:0.0.19"
bstats = "org.bstats:bstats-bukkit:3.1.0"
vault = "com.github.MilkBowl:VaultAPI:1.7.1"
packetevents = "com.github.retrooper:packetevents-spigot:2.10.0"
placeholderapi = "me.clip:placeholderapi:2.11.6"
towny = "com.palmergames.bukkit.towny:towny:0.101.2.7"

# Testing
junit-bom = "org.junit:junit-bom:5.13.4"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }
slf4j = "org.slf4j:slf4j-simple:2.0.17"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.21.3"
testcontainers-jupiter = { module = "org.testcontainers:junit-jupiter" }

[bundles]
junit = ["junit-jupiter", "junit-platform"]
testcontainers = ["testcontainers-jupiter"]

[plugins]
shadow = "com.gradleup.shadow:9.0.2"
run-paper = "xyz.jpenilla.run-paper:2.3.1"
plugin-yml-bukkit = "de.eldoria.plugin-yml.bukkit:0.7.1"
plugin-yml-paper = "de.eldoria.plugin-yml.paper:0.7.1"
